match:
  - default
widgets:
  - id: open-url
    kind: button
    label: Open example.com
    icon:
      source: lucide
      name: globe
    grid: [0, 0, 1, 1]
    action:
      shell: "xdg-open https://example.com"
  - id: audio-toggle
    kind: button
    label: VLC Play/Pause
    icon:
      source: lucide
      name: media-play
    grid: [1, 0, 1, 1]
    action:
      dbus: "org.mpris.MediaPlayer2.vlc:/org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"
  - id: xterm
    kind: button
    label: xterm
    icon:
      source: lucide
      name: terminal
    grid: [2, 0, 1, 1]
    action:
      terminal: "xterm"
  - id: tilix
    kind: button
    label: tilix
    icon:
      source: lucide
      name: terminal
    grid: [3, 0, 1, 1]
    action:
      terminal: "tilix"
  - id: send-key
    kind: button
    label: Send Ctrl+T
    icon:
      source: lucide
      name: keyboard
    grid: [0, 1, 1, 1]
    action:
      key: "ctrl+t"
