#!/usr/bin/env bash
# Make a `git worktree` checkout of deckd dev-ready, and diagnose one that
# isn't. Driven by `just worktree-adopt` / `worktree-doctor` / `worktree-list`.
#
# Why this exists: the daemon, tests and scripts already resolve their paths
# from the file's own location, so *code* needs nothing for worktrees. What a
# fresh worktree lacks is everything git deliberately doesn't carry across:
#
#   - the host's port space is shared, so two worktrees both default to
#     :8765/:5173/:8975 and collide;
#   - `.envrc`, `.flox/`, `.venv/`, `client/node_modules/` and `client/.tls/`
#     are all gitignored, so a new checkout has no toolchain, no venv, no
#     dependencies and no TLS cert.
#
# `adopt` fixes all of that in one idempotent pass. The name follows the
# convention in the sibling monorepo: worktrees created by an agent harness
# (Paseo, Cursor) or a bare `git worktree add` get *adopted* after the fact,
# rather than being created by a bespoke wrapper.
#
# Bash 3.2 compatible (macOS ships 3.2): no associative arrays, no ${x,,}.
set -euo pipefail

# Port bases. Offset 0 is the primary checkout, so its ports are exactly
# today's defaults and nothing about the main checkout changes. Linked
# worktrees take the lowest free offset >= 1, applied to all three bases at
# once so a worktree's ports stay mentally grouped (8766/5174/8976).
BASE_DECKD=8765
BASE_VITE=5173
BASE_E2E=8975
MAX_OFFSET=64

# Gitignored paths worth carrying from the primary checkout into a new
# worktree. Certs are the expensive one: `just dev-client-tailscale`
# provisions them with sudo, and they're host-wide, so re-provisioning per
# worktree is pure friction. Overridable by a .worktreeinclude file.
DEFAULT_INCLUDE="client/.tls"

say() { printf '%s\n' "$*"; }
warn() { printf 'warn: %s\n' "$*" >&2; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

repo_root() { git rev-parse --show-toplevel; }

# First entry of `git worktree list` is always the main working tree.
primary_root() { git worktree list --porcelain | awk '/^worktree /{print $2; exit}'; }

all_worktrees() { git worktree list --porcelain | awk '/^worktree /{print $2}'; }

is_primary() { [ "$(repo_root)" = "$(primary_root)" ]; }

# Read one KEY=VALUE out of a dotenv file. Empty output when absent.
env_value() {
    local file="$1" key="$2"
    [ -f "$file" ] || return 0
    sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\([^[:space:]#]*\).*/\1/p" "$file" | tail -n1
}

# The offset a checkout has already claimed, or empty if it has claimed none.
# The primary implicitly owns offset 0 whether or not it has a .env.
offset_of() {
    local dir="$1" port
    port="$(env_value "$dir/.env" DECKD_PORT)"
    if [ -n "$port" ]; then
        echo $(( port - BASE_DECKD ))
        return 0
    fi
    # Must not leak a non-zero status: callers assign this in a command
    # substitution, where `set -e` treats a bare failure as fatal — which
    # would abort `doctor` at the first unassigned worktree it looked at.
    [ "$dir" = "$(primary_root)" ] && echo 0
    return 0
}

# True when nothing is listening on the port. `ss` on Linux, `lsof` on macOS
# (the Justfile's `kill` recipe already depends on lsof). With neither, skip
# the liveness check — the .env scan below is the primary mechanism and this
# is only a guard against ports held by non-worktree processes.
port_free() {
    local p="$1"
    if command -v ss >/dev/null 2>&1; then
        ! ss -ltnH "sport = :$p" 2>/dev/null | grep -q .
    elif command -v lsof >/dev/null 2>&1; then
        ! lsof -ti "tcp:$p" >/dev/null 2>&1
    else
        return 0
    fi
}

# Pick this worktree's offset: an already-written .env wins (adopt is
# idempotent and must never renumber a worktree out from under a running
# daemon), then the primary's implicit 0, then the lowest offset not claimed
# by a sibling .env and whose three ports are all unbound.
allocate_offset() {
    local self existing other o claimed used
    self="$(repo_root)"
    existing="$(offset_of "$self")"
    if [ -n "$existing" ]; then echo "$existing"; return 0; fi

    claimed=""
    for other in $(all_worktrees); do
        [ "$other" = "$self" ] && continue
        o="$(offset_of "$other")"
        [ -n "$o" ] && claimed="$claimed $o"
    done

    o=1
    while [ "$o" -le "$MAX_OFFSET" ]; do
        used=0
        case " $claimed " in *" $o "*) used=1 ;; esac
        if [ "$used" -eq 0 ] \
            && port_free $(( BASE_DECKD + o )) \
            && port_free $(( BASE_VITE + o )) \
            && port_free $(( BASE_E2E + o )); then
            echo "$o"; return 0
        fi
        o=$(( o + 1 ))
    done
    die "no free port offset below $MAX_OFFSET; clean up stale worktrees or daemons"
}

write_env() {
    local offset="$1" root="$2"
    cat > "$root/.env" <<EOF
# Generated by \`just worktree-adopt\`. Gitignored, per-worktree, and loaded
# automatically by every just recipe (\`set dotenv-load\` in the Justfile).
# Offset $offset from the default ports, so this worktree's daemon, Vite dev
# server and Playwright fixture can run alongside every sibling checkout.
# An explicit env var still wins: \`DECKD_PORT=9000 just dev\`.
DECKD_PORT=$(( BASE_DECKD + offset ))
VITE_PORT=$(( BASE_VITE + offset ))
DECKD_E2E_PORT=$(( BASE_E2E + offset ))
EOF
}

# Wire direnv up to the *primary* checkout's flox environment. A worktree has
# no .flox/ of its own, and direnv's stdlib `use flox` requires a local one —
# so call `flox activate -d` directly and dump the result. Crucially flox
# leaves $PWD alone, so the manifest's `$PWD/.venv` profile hook still picks
# up this worktree's own venv: shared toolchain, isolated venv, which is what
# an editable `pip install -e .` needs (it bakes in an absolute path).
write_envrc() {
    local root="$1" primary="$2"
    cat > "$root/.envrc" <<EOF
# Generated by \`just worktree-adopt\`. Gitignored and safe to edit.
# This worktree has no .flox/ of its own, so resolve the toolchain from the
# primary checkout's environment. \$PWD stays here, so the manifest's
# \$PWD/.venv hook still finds *this* worktree's venv.
if [ -d "\$PWD/.flox" ]; then
    use flox
else
    direnv_load flox activate -d "$primary" -- "\$direnv" dump
fi
EOF
}

# Copy gitignored-but-worth-sharing files from the primary checkout.
copy_included() {
    local root="$1" primary="$2" list rel
    list="$DEFAULT_INCLUDE"
    [ -f "$primary/.worktreeinclude" ] && \
        list="$(grep -v '^[[:space:]]*#' "$primary/.worktreeinclude" | grep -v '^[[:space:]]*$' || true)"
    for rel in $list; do
        [ -e "$primary/$rel" ] || continue
        if [ -e "$root/$rel" ]; then continue; fi
        mkdir -p "$(dirname "$root/$rel")"
        cp -R "$primary/$rel" "$root/$rel"
        say "  copied $rel from the primary checkout"
    done
}

cmd_ports() {
    local root offset
    root="$(repo_root)"
    offset="$(allocate_offset)"
    echo "DECKD_PORT=$(( BASE_DECKD + offset ))"
    echo "VITE_PORT=$(( BASE_VITE + offset ))"
    echo "DECKD_E2E_PORT=$(( BASE_E2E + offset ))"
}

cmd_adopt() {
    local install=1 force=0 root primary offset
    while [ $# -gt 0 ]; do
        case "$1" in
            --no-install) install=0 ;;
            --install) install=1 ;;
            --force) force=1 ;;
            *) die "unknown flag: $1 (want --no-install / --force)" ;;
        esac
        shift
    done

    root="$(repo_root)"
    primary="$(primary_root)"

    if is_primary; then
        say "primary checkout ($root) — keeps the default ports (:$BASE_DECKD/:$BASE_VITE)."
    else
        [ "$force" -eq 1 ] && rm -f "$root/.env"
        offset="$(allocate_offset)"
        write_env "$offset" "$root"
        say "ports: deckd :$(( BASE_DECKD + offset ))  vite :$(( BASE_VITE + offset ))  e2e :$(( BASE_E2E + offset ))  -> .env"

        # Only offer direnv when the primary is set up for it; the repo
        # doesn't prescribe direnv or flox, and .envrc is gitignored.
        if [ -f "$primary/.envrc" ] || [ -d "$primary/.flox" ]; then
            if [ -f "$root/.envrc" ] && [ "$force" -eq 0 ]; then
                say "  .envrc already present, left alone (--force to rewrite)"
            else
                write_envrc "$root" "$primary"
                say "  wrote .envrc -> flox env from $primary"
                command -v direnv >/dev/null 2>&1 && direnv allow "$root" 2>/dev/null || true
            fi
        fi
        copy_included "$root" "$primary"
    fi

    if [ "$install" -eq 1 ]; then
        say "installing dependencies (\`just setup\`) — pass --no-install to skip"
        ( cd "$root" && just setup )
    else
        say "skipped dependency install; run \`just setup\` in this worktree before testing"
    fi
    say "adopted. \`just worktree-doctor\` verifies it."
}

ok() { printf '  ok    %s\n' "$*"; }
bad() { printf '  FAIL  %s\n' "$*"; DOCTOR_FAILED=1; }
note() { printf '  warn  %s\n' "$*"; }

cmd_doctor() {
    local root primary offset other o self_o
    DOCTOR_FAILED=0
    root="$(repo_root)"
    primary="$(primary_root)"
    say "worktree: $root ($(git rev-parse --abbrev-ref HEAD))"

    if is_primary; then
        ok "primary checkout — uses the default ports"
    else
        if [ -f "$root/.env" ]; then
            ok "ports: deckd :$(env_value "$root/.env" DECKD_PORT)" \
               "vite :$(env_value "$root/.env" VITE_PORT)" \
               "e2e :$(env_value "$root/.env" DECKD_E2E_PORT)"
        else
            bad "no .env — this worktree shares :$BASE_DECKD/:$BASE_VITE with the primary. Fix: just worktree-adopt"
        fi
        # Cross-check for two worktrees on the same offset (hand-edited .env,
        # or a worktree adopted while a sibling was mid-adopt).
        self_o="$(offset_of "$root")"
        if [ -n "$self_o" ]; then
            for other in $(all_worktrees); do
                [ "$other" = "$root" ] && continue
                o="$(offset_of "$other")"
                [ "$o" = "$self_o" ] && bad "port offset $self_o also claimed by $other. Fix: just worktree-adopt --force"
            done
        fi
        if [ -f "$root/.envrc" ]; then
            ok ".envrc present"
        elif [ -f "$primary/.envrc" ] || [ -d "$primary/.flox" ]; then
            note "no .envrc — the primary uses direnv/flox but this worktree won't auto-activate"
        fi
    fi

    command -v just >/dev/null 2>&1 && ok "just on PATH" || bad "just not on PATH"
    if command -v uv >/dev/null 2>&1; then ok "uv on PATH"; else
        bad "uv not on PATH — \`just setup\` can't build the venv. Fix: activate the env (direnv/flox) first"
    fi
    command -v node >/dev/null 2>&1 && ok "node on PATH ($(node --version))" || bad "node not on PATH"

    if [ -x "$root/.venv/bin/deckd" ]; then
        ok ".venv present with deckd installed"
    elif [ -d "$root/.venv" ]; then
        bad ".venv exists but has no deckd entry point. Fix: just setup"
    elif command -v deckd >/dev/null 2>&1; then
        note "no ./.venv; deckd resolves from the active env ($(command -v deckd))"
    else
        bad "no ./.venv and no deckd on PATH. Fix: just setup"
    fi

    [ -d "$root/client/node_modules" ] && ok "client/node_modules present" \
        || bad "no client/node_modules. Fix: just setup"

    if [ "$DOCTOR_FAILED" -eq 1 ]; then
        say "not ready."
        exit 1
    fi
    say "ready."
}

cmd_list() {
    local root self o dport vport state branch
    self="$(repo_root)"
    printf '%-2s %-36s %-22s %-6s %-6s %s\n' "" BRANCH PATH DECKD VITE STATE
    for root in $(all_worktrees); do
        o="$(offset_of "$root")"
        if [ -n "$o" ]; then
            dport="$(( BASE_DECKD + o ))"
            vport="$(( BASE_VITE + o ))"
        else
            dport="-"
            vport="-"
        fi
        state="not adopted"
        if [ -d "$root/client/node_modules" ] && { [ -d "$root/.venv" ] || [ "$root" = "$(primary_root)" ]; }; then
            state="ready"
        elif [ -n "$o" ]; then
            state="ports only"
        fi
        branch="$(git -C "$root" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
        printf '%-2s %-36s %-22s %-6s %-6s %s\n' \
            "$([ "$root" = "$self" ] && echo '*' || echo ' ')" \
            "$branch" "$(basename "$root")" "$dport" "$vport" "$state"
    done
}

case "${1:-}" in
    ports) shift; cmd_ports "$@" ;;
    adopt) shift; cmd_adopt "$@" ;;
    doctor) shift; cmd_doctor "$@" ;;
    list) shift; cmd_list "$@" ;;
    *) die "usage: scripts/worktree.sh {adopt [--no-install] [--force] | doctor | list | ports}" ;;
esac
